### ISSUE TITLE
Rewrite?

### ISSUE THREAD

**Issue by xZeroMCPE** [MCrafterss/TradingPro#1]
Can this call be rewrite? The source itself seems confusing. And i can prob help rewrite it and get it working.

**Comment by HittmanA** [comment]
Yes of course! Any help is greatly appreciated. Basically how the code "should" work is 
1. User sends trade request to another player
2. Other player accepts trade request (or denies it)
3. Items are switched in corresponding amounts

**Comment by HittmanA** [comment]
Just let me know what I should do to rewrite it.

**Comment by xZeroMCPE** [comment]
@HittmanA  

Yea,

To make it more simple the item the player is holding is the one that is being trade?

**Comment by HittmanA** [comment]
Yes.

**Comment by xZeroMCPE** [comment]
@HittmanA  Do i have permission to delete somethings and help rewrite it?

**Comment by HittmanA** [comment]
Of course! Everyone in MCrafters has permission to deleted and rewrite it.

**Comment by xZeroMCPE** [comment]
@HittmanA Alright, and you do have a fast response rate :+1:

**Comment by SinlesFlyer376** [comment]
Dm me xZero

**Comment by remotevase** [comment]
what do ya need?
